CREATE DATABASE LOGIN_PAGINA_WEB;

USE LOGIN_PAGINA_WEB;

CREATE TABLE LOGIN(
	CORREO VARCHAR(30) primary KEY,
    CONTRASENIA VARCHAR(16),
    ID_USUARIO INT
);

INSERT INTO LOGIN_PAGINA_WEB.LOGIN(CORREO, CONTRASENIA, ID_USUARIO)
VALUE('ADMIN@ADMIN.ADMIN','ADMIN.ADMIN','5')

SELECT CORREO, CONTRASENIA, ID_USUARIO FROM LOGIN_PAGINA_WEB.LOGIN WHERE CORREO='' AND CONTRASENIA=''